export const videosPlaylists: any = [
    [
        {
            id: "1",
            titleVideo: "I Drew Every Day for 365 Days..... *it was painful*",
            channelName: "PewDiePie",
            videoPreview: require('../../../../assets/images/video-images/previews/Thumbnail.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar.png'),
            views: '1.4M',
            date: '1 day',
            time: '16:52',
        },
        {
            id: "2",
            titleVideo: "6 UI Hacks I Wish I Knew As A Beginner",
            channelName: "Tim Gabe",
            videoPreview: require('../../../../assets/images/video-images/previews/image.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar-1.png'),
            views: '835K',
            date: '1 year',
            time: '11:11',
        },
    ],
    [
        {
            id: "1",
            titleVideo: "I Drew Every Day for 365 Days..... *it was painful*",
            channelName: "PewDiePie",
            videoPreview: require('../../../../assets/images/video-images/previews/Thumbnail.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar.png'),
            views: '1.4M',
            date: '1 day',
            time: '16:52',
        },                
        {
            id: "2",
            titleVideo: "6 UI Hacks I Wish I Knew As A Beginner",
            channelName: "Tim Gabe",
            videoPreview: require('../../../../assets/images/video-images/previews/image.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar-1.png'),
            views: '835K',
            date: '1 year',
            time: '11:11',
        },
        {
            id: "3",
            titleVideo: "I Drew Every Day for 365 Days..... *it was painful*",
            channelName: "PewDiePie",
            videoPreview: require('../../../../assets/images/video-images/previews/Thumbnail.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar.png'),
            views: '1.4M',
            date: '1 day',
            time: '16:52',
        },
        {
            id: "4",
            titleVideo: "6 UI Hacks I Wish I Knew As A Beginner",
            channelName: "Tim Gabe",
            videoPreview: require('../../../../assets/images/video-images/previews/image.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar-1.png'),
            views: '835K',
            date: '1 year',
            time: '11:11',
        },                
        {
            id: "5",
            titleVideo: "I Drew Every Day for 365 Days..... *it was painful*",
            channelName: "PewDiePie",
            videoPreview: require('../../../../assets/images/video-images/previews/Thumbnail.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar.png'),
            views: '1.4M',
            date: '1 day',
            time: '16:52',
        }, 
        {
            id: "6",
            titleVideo: "6 UI Hacks I Wish I Knew As A Beginner",
            channelName: "Tim Gabe",
            videoPreview: require('../../../../assets/images/video-images/previews/image.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar-1.png'),
            views: '835K',
            date: '1 year',
            time: '11:11',
        }, 
        {
            id: "7",
            titleVideo: "I Drew Every Day for 365 Days..... *it was painful*",
            channelName: "PewDiePie",
            videoPreview: require('../../../../assets/images/video-images/previews/image-1.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar.png'),
            views: '1.4',
            date: '1',
            time: '16:52',
        },    
    ],
    [        
        {
            id: "1",
            titleVideo: "I Drew Every Day for 365 Days..... *it was painful*",
            channelName: "PewDiePie",
            videoPreview: require('../../../../assets/images/video-images/previews/image-1.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar.png'),
            views: '1.4',
            date: '1',
            time: '16:52',
        },
        {
            id: "2",
            titleVideo: "6 UI Hacks I Wish I Knew As A Beginner",
            channelName: "Tim Gabe",
            videoPreview: require('../../../../assets/images/video-images/previews/image.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar-1.png'),
            views: '835K',
            date: '1 year',
            time: '11:11',
        },
        {
            id: "3",
            titleVideo: "I Drew Every Day for 365 Days..... *it was painful*",
            channelName: "PewDiePie",
            videoPreview: require('../../../../assets/images/video-images/previews/Thumbnail.png'),
            avatar: require('../../../../assets/images/video-images/avatars/Avatar.png'),
            views: '1.4M',
            date: '1 day',
            time: '16:52',
        },
    ],  

];